# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.IntegerField(db_index=True, default=None, null=True)),
                ('arch', models.IntegerField(db_index=True, default=None, null=True)),
                ('topo', models.IntegerField(db_index=True, default=None, null=True)),
                ('homsf', models.IntegerField(db_index=True, default=None, null=True)),
                ('s35', models.IntegerField(db_index=True, default=None, null=True)),
                ('s60', models.IntegerField(default=None, null=True)),
                ('s95', models.IntegerField(default=None, null=True)),
                ('s100', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(db_index=True, max_length=7)),
                ('domain_length', models.IntegerField(default=0, null=True)),
                ('resolution', models.FloatField(default=0, null=True)),
                ('nDOPE', models.FloatField(default=0, null=True)),
                ('raw_DOPE', models.FloatField(default=0, null=True)),
            ],
        ),

        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('letter', models.CharField(default=None, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='s35_rep',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tst.domain')),
            ],
            bases=('tst.domain',),
        ),
        migrations.AddField(
            model_name='domain',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.classification'),
        ),
        ### Manually altered the field to OneToOne
        migrations.AlterField(
            model_name='domain',
            name='classification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tst.classification'),
        ),
        migrations.AddField(
            model_name='classification',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.level'),
        ),
        migrations.AddField(
            model_name='classification',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tst.classification'),
        ),
        migrations.AddField(
            model_name='classification',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tst.version'),
        ),

        migrations.CreateModel(
            name='domain_stat',
            fields=[
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tst.domain')),
                ('DOPE', models.FloatField(null=True)),
                ('nDOPE', models.FloatField(null=True)),
                ('nbpair_count', models.IntegerField(null=True)),
                ('atom_count', models.IntegerField(null=True)),
                ('res_count', models.IntegerField(null=True)),
                ('maha_dist',models.FloatField(null=True)),
                ('pcx',models.FloatField(null=True)),
                ('pcy',models.FloatField(null=True)),
            ],
        ),


        migrations.CreateModel(
            name='node_stat',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tst.classification')),
            ],
        ),
        
        migrations.AddField(
            model_name='node_stat',
            name='Rsq_NBcount_Acount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='node_stat',
            name='Rsq_NBcount_Rcount',
            field=models.FloatField(null=True),
        ),

    ]
