# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0006_load_nDOPE'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_stat',
            fields=[
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tst.domain')),
                ('DOPE', models.FloatField(null=True)),
                ('nDOPE', models.FloatField(null=True)),
                ('nbpair_count', models.IntegerField(null=True)),
                ('atom_count', models.IntegerField(null=True)),
                ('res_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='node_stat',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tst.classification')),
            ],
        ),
        
        migrations.AddField(
            model_name='node_stat',
            name='Rsq_NBcount_Acount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='node_stat',
            name='Rsq_NBcount_Rcount',
            field=models.FloatField(null=True),
        ),

        

    ]
