# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0006_load_nDOPE'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='classification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tst.classification'),
        ),
    ]
